/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#00325c",
        "on-tertiary-fixed-variant": "#004882",
        "secondary": "#666000",
        "outline-variant": "#bec8d2",
        "inverse-primary": "#8cceff",
        "on-surface-variant": "#3e4850",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-variant": "#d3e4fe",
        "on-background": "#0b1c30",
        "tertiary": "#27609d",
        "on-primary-fixed-variant": "#004b6f",
        "on-tertiary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#4d4800",
        "surface-container-high": "#dce9ff",
        "tertiary-container": "#689bdc",
        "surface-container": "#e5eeff",
        "primary": "#006492",
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#cae6ff",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#1e1c00",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#a3c9ff",
        "secondary-fixed-dim": "#d5ca00",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#001c38",
        "outline": "#6e7882",
        "primary-fixed-dim": "#8cceff",
        "surface-tint": "#006492",
        "tertiary-fixed": "#d3e4ff",
        "background": "#f8f9ff",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#00344f",
        "primary-container": "#00a2e9",
        "on-secondary-container": "#6a6500",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001e2f",
        "secondary-fixed": "#f3e700",
        "secondary-container": "#f0e400",
        "on-surface": "#0b1c30"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "xs": "4px",
        "lg": "24px",
        "md": "16px",
        "2xl": "48px",
        "margin-mobile": "16px",
        "base": "4px",
        "xl": "32px",
        "margin-desktop": "32px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "headline-sm": ["Inter"],
        "display-lg": ["Inter"],
        "title-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "code-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "title-lg": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [],
}